persistence:
  type: pvc
  enabled: true

adminUser: admin
adminPassword: admin

plugins:
  - alexanderzobnin-zabbix-app
  - grafana-clock-panel

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.loki.svc.cluster.local
        editable: true
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir-nginx.mimir.svc/prometheus
        editable: true
