minio:
  enabled: true
  replicas: 3
  drivesPerNode: 2
  rootUser: admin
  rootPassword: admin
  persistence:
    size: 10Gi
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi

loki:
  auth_enabled: false
