minio:
  enabled: true
  replicas: 3
  drivesPerNode: 1
  rootUser: admin
  rootPassword: admin
  persistence:
    size: 50Gi
  resources:
    requests:
      cpu: 500m
      memory: 512Mi

loki:
  auth_enabled: false
